import type User from './User'

export enum Craft {
  KNIT = 'KNIT',
  LOOM_KNIT = 'LOOM_KNIT',
  MACHINE_KNIT = 'MACHINE_KNIT',
  CROCHET = 'CROCHET',
  TUNISIAN_CROCHET = 'TUNISIAN_CROCHET'
}

export enum YarnWeight {
  THREAD = 'THREAD',
  LACE = 'LACE',
  LIGHT_FINGERING = 'LIGHT_FINGERING',
  FINGERING = 'FINGERING',
  SPORT = 'SPORT',
  DK = 'DK',
  WORSTED = 'WORSTED',
  ARAN = 'ARAN',
  BULKY = 'BULKY',
  SUPER_BULKY = 'SUPER_BULKY',
  JUMBO = 'JUMBO',
  ROVING = 'ROVING',
  OTHER = 'OTHER'
}

export enum Attribute {
  COLORWORK = 'COLORWORK',
  SEAMING = 'SEAMING',
  TRADITIONAL = 'TRADITIONAL',
  LACE = 'LACE',
  MATURE = 'MATURE',
  FILLED = 'FILLED'
}

export enum Category {
  CLOTHING_BOTTOMS_LEGGINGS,
  CLOTHING_BOTTOMS_PANTS,
  CLOTHING_BOTTOMS_SHORTS,
  CLOTHING_BOTTOMS_SKIRTS,
  CLOTHING_DRESSES,
  CLOTHING_INTIMATES,
  CLOTHING_INTIMATES_BRAS,
  CLOTHING_OUTERWEAR,
  CLOTHING_OTHER,
  CLOTHING_SLEEPWEAR,
  CLOTHING_SLEEPWEAR_ROBES,
  CLOTHING_TOPS_SWEATERS_CARDIGANS,
  CLOTHING_TOPS_SWEATERS_DUSTERS,
  CLOTHING_TOPS_SWEATERS_PULLOVERS,
  CLOTHING_TOPS_TANKS,
  CLOTHING_TOPS_TEES,
  CLOTHING_TOPS_VESTS,
  ACCESSORIES_BAGS,
  ACCESSORIES_FEETLEGS_LEGWARMERS,
  ACCESSORIES_FEETLEGS_SOCKS,
  ACCESSORIES_FEETLEGS_SLIPPERS,
  ACCESSORIES_FEETLEGS,
  ACCESSORIES_HANDS_GLOVES,
  ACCESSORIES_HANDS_GLOVES_FINGERLESS,
  ACCESSORIES_HANDS_MITTENS,
  ACCESSORIES_HANDS_ARMWARMERS,
  ACCESSORIES_HEAD_HEADBANDS,
  ACCESSORIES_HEAD_HATS,
  ACCESSORIES_JEWELRY,
  ACCESSORIES_OTHER,
  HOME_BLANKETS,
  HOME_COZIES,
  HOME_COASTERS,
  HOME_DECORATIVE,
  HOME_OTHER,
  HOME_PILLOWS,
  HOME_POTHOLDERS,
  HOME_TOWELS,
  PET_ACCESSORIES,
  PET_BEDDING,
  PET_CLOTHING,
  PET_OTHER,
  PET_TOYS,
  TOYS_AMIGURUMI,
  TOYS_DOLLS,
  TOYS_GAMES,
  TOYS_OTHER,
  TOYS_SOFTIES,
  COMPONENTS_APPLIQUES,
  COMPONENTS_CHARTS,
  COMPONENTS_EDGING,
  COMPONENTS_GRANNYSQUARES,
  COMPONENTS_OTHER,
  COMPONENTS_STITCHPATTERNS,
  COMPONENTS_TECHNIQUES,
  OTHER
}

type Meterage = [min: number, max: number]

export interface PatternTag {
  id: string
  name: string
  patterns?: Pattern[]
}

export default interface Pattern {
  id: string
  name: string
  creator: User
  createdAt: Date
  updatedAt: Date
  publishedAt?: Date
  craft: Craft
  category: Category[]
  yarnWeight?: YarnWeight
  gaugeRows?: number
  gaugeStitches?: number
  gaugeSizeInCm?: number
  suggestedYarn?: string
  meterage?: Meterage
  needleSize: number[]
  colorCount?: number
  attributes: Attribute[]
  tags: PatternTag[]
}

export type PatternFields = keyof Pattern
