services:
  db:
    image: postgres
    container_name: knitly
    environment:
      POSTGRES_PASSWORD: knitadmin
      POSTGRES_USER: postgres
      POSTGRES_DB: knitly
    ports:
      - '5433:5432'
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata: