-- CreateEnum
CREATE TYPE "YarnWeight" AS ENUM ('THREAD', 'LACE', 'LIGHT_FINGERING', 'FINGERING', 'SPORT', 'DK', 'WORSTED', 'ARAN', 'BULKY', 'SUPER_BULKY', 'JUMBO', 'ROVING', 'OTHER');

-- CreateEnum
CREATE TYPE "Craft" AS ENUM ('KNIT', 'LOOM_KNIT', 'MACHINE_KNIT', 'CROCHET', 'TUNISIAN_CROCHET');

-- CreateEnum
CREATE TYPE "Attribute" AS ENUM ('COLORWORK', 'SEAMING', 'TRADITIONAL', 'LACE', 'MATURE', 'FILLED');

-- CreateEnum
CREATE TYPE "Category" AS ENUM ('CLOTHING_BOTTOMS_LEGGINGS', 'CLOTHING_BOTTOMS_PANTS', 'CLOTHING_BOTTOMS_SHORTS', 'CLOTHING_BOTTOMS_SKIRTS', 'CLOTHING_DRESSES', 'CLOTHING_INTIMATES', 'CLOTHING_INTIMATES_BRAS', 'CLOTHING_OUTERWEAR', 'CLOTHING_OTHER', 'CLOTHING_SLEEPWEAR', 'CLOTHING_SLEEPWEAR_ROBES', 'CLOTHING_TOPS_SWEATERS_CARDIGANS', 'CLOTHING_TOPS_SWEATERS_DUSTERS', 'CLOTHING_TOPS_SWEATERS_PULLOVERS', 'CLOTHING_TOPS_TANKS', 'CLOTHING_TOPS_TEES', 'CLOTHING_TOPS_VESTS', 'ACCESSORIES_BAGS', 'ACCESSORIES_FEETLEGS_LEGWARMERS', 'ACCESSORIES_FEETLEGS_SOCKS', 'ACCESSORIES_FEETLEGS_SLIPPERS', 'ACCESSORIES_FEETLEGS', 'ACCESSORIES_HANDS_GLOVES', 'ACCESSORIES_HANDS_GLOVES_FINGERLESS', 'ACCESSORIES_HANDS_MITTENS', 'ACCESSORIES_HANDS_ARMWARMERS', 'ACCESSORIES_HEAD_HEADBANDS', 'ACCESSORIES_HEAD_HATS', 'ACCESSORIES_JEWELRY', 'ACCESSORIES_OTHER', 'HOME_BLANKETS', 'HOME_COZIES', 'HOME_COASTERS', 'HOME_DECORATIVE', 'HOME_OTHER', 'HOME_PILLOWS', 'HOME_POTHOLDERS', 'HOME_TOWELS', 'PET_ACCESSORIES', 'PET_BEDDING', 'PET_CLOTHING', 'PET_OTHER', 'PET_TOYS', 'TOYS_AMIGURUMI', 'TOYS_DOLLS', 'TOYS_GAMES', 'TOYS_OTHER', 'TOYS_SOFTIES', 'COMPONENTS_APPLIQUES', 'COMPONENTS_CHARTS', 'COMPONENTS_EDGING', 'COMPONENTS_GRANNYSQUARES', 'COMPONENTS_OTHER', 'COMPONENTS_STITCHPATTERNS', 'COMPONENTS_TECHNIQUES', 'OTHER');

-- CreateTable
CREATE TABLE "Pattern" (
    "id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "creatorId" UUID NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "publishedAt" TIMESTAMP(3),
    "craft" "Craft" NOT NULL,
    "category" "Category"[] DEFAULT ARRAY['OTHER']::"Category"[],
    "yarnWeight" "YarnWeight"[] DEFAULT ARRAY[]::"YarnWeight"[],
    "rowGauge" TEXT,
    "stitchGauge" TEXT,
    "suggestedYarn" TEXT,
    "meterage" INTEGER[],
    "needleSize" INTEGER NOT NULL,
    "colorCount" INTEGER NOT NULL,
    "attributes" "Attribute"[],

    CONSTRAINT "Pattern_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AssignedPatternTag" (
    "id" UUID NOT NULL,
    "patternId" UUID NOT NULL,
    "tagId" UUID NOT NULL,

    CONSTRAINT "AssignedPatternTag_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PatternTag" (
    "id" UUID NOT NULL,
    "name" TEXT NOT NULL,

    CONSTRAINT "PatternTag_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Pattern" ADD CONSTRAINT "Pattern_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssignedPatternTag" ADD CONSTRAINT "AssignedPatternTag_patternId_fkey" FOREIGN KEY ("patternId") REFERENCES "Pattern"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AssignedPatternTag" ADD CONSTRAINT "AssignedPatternTag_tagId_fkey" FOREIGN KEY ("tagId") REFERENCES "PatternTag"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
